name: Checagem de Sintaxe
on: [push]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v4

      - name: 2. Instalar o Node.js e NPM
        uses: actions/setup-node@v4
        with:
          node-version: '24.14.0'

      - name: 3. Instalar dependências do Vue
        working-directory: ./frontend
        run: npm install

      - name: 4. Executar o Linter (ESLint)
        working-directory: ./frontend
        run: npm run lint

      - name: 5. Executar o build
        working-directory: ./frontend
        run: npm run build

      - name: 6. Executar o Cypress
        working-directory: ./frontend
        run: npm run test:e2e

  lint-backend:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testes_db
      DB_USERNAME: root
      DB_PASSWORD: root
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testes_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v4

      - name: 2. Instalar o PHP e Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql
          coverage: none

      - name: 3. Instalar dependências do Laravel
        working-directory: ./backend
        run: composer install --prefer-dist --no-interaction

      - name: 4. Executar o Pint
        working-directory: ./backend
        run: vendor/bin/pint --test

      - name: 5. Preparando o banco de dados
        working-directory: ./backend
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --force

      - name: 6. Executando o PHPUnit
        working-directory: ./backend
        run: vendor/bin/phpunit